version: '3.8'
name: "developer_scrape_production"
services:
  app:
    container_name: django_app_prod
    image: developer_scrape_production-app
    build: .
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 2222
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db_prod
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
  nginx:
    container_name: nginx_prod
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - app
volumes:
  postgres_data:
  static_volume:
