version: '3.8'

services:
  app:
    container_name: django_app_prod
    build: .
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 2222
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db_prod
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome_driver_prod
    ports:
      - "4444:4444"
    hostname: chrome
    privileged: true
    shm_size: 2g
    restart: always
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=20
  nginx:
    container_name: nginx_prod
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - app
volumes:
  postgres_data:
  static_volume:
