# Generated by Django 4.2.3 on 2023-07-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flat_browser.developer'),
            preserve_default=False,
        ),
    ]
