# Generated by Django 4.2.3 on 2023-07-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0002_flat_developer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['developer', 'name'], 'select_on_save': True},
        ),
        migrations.AlterOrderWithRespectTo(
            name='investment',
            order_with_respect_to=None,
        ),
    ]
