# Generated by Django 4.2.3 on 2023-07-13 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0003_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('free', 'wolne'), ('sold', 'sprzedane'), ('reserved', 'zarezerwowane')], max_length=50),
        ),
    ]
