# Generated by Django 4.2.3 on 2023-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0004_alter_flat_area_alter_flat_floor_alter_flat_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('wolne', 'wolne'), ('sprzedane', 'sprzedane'), ('zarezerwowane', 'zarezerwowane')], max_length=50),
        ),
    ]
