# Generated by Django 4.2.4 on 2023-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0005_alter_flat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='scrape_attr',
            field=models.CharField(default='costam', max_length=50),
            preserve_default=False,
        ),
    ]
