# Generated by Django 4.2.4 on 2023-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0006_developer_scrape_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
