# Generated by Django 4.2.4 on 2023-08-18 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_browser', '0007_alter_flat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('wolne', 'wolne'), ('sprzedane', 'sprzedane'), ('zarezerwowane', 'zarezerwowane')], max_length=50, null=True),
        ),
    ]
